import 'package:flutter/material.dart';

class MoodIcons {
  static final Map<String, IconData> _moodMap = {
    '开心': Icons.sentiment_very_satisfied,
    '高兴': Icons.sentiment_very_satisfied,
    '快乐': Icons.sentiment_very_satisfied,
    '愉快': Icons.sentiment_satisfied,
    '欢乐': Icons.sentiment_very_satisfied,
    '喜悦': Icons.sentiment_very_satisfied,
    '兴奋': Icons.sentiment_very_satisfied,
    '幸福': Icons.favorite,
    '满足': Icons.sentiment_satisfied,
    '舒畅': Icons.sentiment_satisfied,
    '惬意': Icons.sentiment_satisfied,
    '棒': Icons.thumb_up,
    '好': Icons.sentiment_satisfied,
    '很好': Icons.sentiment_very_satisfied,
    '美滋滋': Icons.sentiment_very_satisfied,
    '乐': Icons.sentiment_very_satisfied,
    '笑': Icons.sentiment_very_satisfied,
    '哈哈': Icons.sentiment_very_satisfied,
    '嘿嘿': Icons.sentiment_satisfied,
    '嘻嘻': Icons.sentiment_very_satisfied,
    'haha': Icons.sentiment_very_satisfied,
    'happy': Icons.sentiment_very_satisfied,
    'good': Icons.sentiment_satisfied,
    'great': Icons.sentiment_very_satisfied,
    '平静': Icons.sentiment_neutral,
    '淡定': Icons.sentiment_neutral,
    '安宁': Icons.sentiment_neutral,
    '安静': Icons.sentiment_neutral,
    '宁静': Icons.sentiment_neutral,
    '平和': Icons.sentiment_neutral,
    '沉稳': Icons.sentiment_neutral,
    '冷静': Icons.sentiment_neutral,
    '一般': Icons.sentiment_neutral,
    '还行': Icons.sentiment_neutral,
    '可以': Icons.sentiment_neutral,
    'ok': Icons.sentiment_neutral,
    'okay': Icons.sentiment_neutral,
    'normal': Icons.sentiment_neutral,
    'fine': Icons.sentiment_neutral,
    'calm': Icons.sentiment_neutral,
    'peaceful': Icons.sentiment_neutral,
    'relaxed': Icons.sentiment_neutral,
    '难过': Icons.sentiment_dissatisfied,
    '伤心': Icons.sentiment_dissatisfied,
    '悲伤': Icons.sentiment_dissatisfied,
    '痛苦': Icons.sentiment_very_dissatisfied,
    '郁闷': Icons.sentiment_dissatisfied,
    '沮丧': Icons.sentiment_dissatisfied,
    '失落': Icons.sentiment_dissatisfied,
    '委屈': Icons.sentiment_dissatisfied,
    '想哭': Icons.sentiment_very_dissatisfied,
    '哭': Icons.sentiment_very_dissatisfied,
    '悲哀': Icons.sentiment_dissatisfied,
    '忧愁': Icons.sentiment_dissatisfied,
    '忧郁': Icons.sentiment_dissatisfied,
    '不开心': Icons.sentiment_dissatisfied,
    '不好': Icons.sentiment_dissatisfied,
    '差': Icons.sentiment_dissatisfied,
    '糟糕': Icons.sentiment_very_dissatisfied,
    'sad': Icons.sentiment_dissatisfied,
    'unhappy': Icons.sentiment_dissatisfied,
    'upset': Icons.sentiment_dissatisfied,
    'depressed': Icons.sentiment_dissatisfied,
    'cry': Icons.sentiment_very_dissatisfied,
    '生气': Icons.sentiment_very_dissatisfied,
    '愤怒': Icons.sentiment_very_dissatisfied,
    '恼火': Icons.sentiment_very_dissatisfied,
    '烦躁': Icons.sentiment_dissatisfied,
    '暴躁': Icons.sentiment_very_dissatisfied,
    '火大': Icons.sentiment_very_dissatisfied,
    'angry': Icons.sentiment_very_dissatisfied,
    'mad': Icons.sentiment_very_dissatisfied,
    'furious': Icons.sentiment_very_dissatisfied,
    'annoyed': Icons.sentiment_dissatisfied,
    'irritated': Icons.sentiment_dissatisfied,
    '累': Icons.battery_alert,
    '疲惫': Icons.battery_alert,
    '疲倦': Icons.battery_alert,
    '困': Icons.bedtime,
    '想睡': Icons.bedtime,
    'tired': Icons.battery_alert,
    'exhausted': Icons.battery_alert,
    'sleepy': Icons.bedtime,
    '焦虑': Icons.psychology,
    '紧张': Icons.psychology,
    '担心': Icons.psychology,
    '害怕': Icons.warning,
    '恐惧': Icons.warning,
    'anxious': Icons.psychology,
    'nervous': Icons.psychology,
    'worried': Icons.psychology,
    'scared': Icons.warning,
    '惊喜': Icons.stars,
    '惊讶': Icons.stars,
    '意外': Icons.stars,
    'surprised': Icons.stars,
    'shocked': Icons.stars,
    'amazed': Icons.stars,
    '爱': Icons.favorite,
    '喜欢': Icons.favorite,
    '心动': Icons.favorite,
    'love': Icons.favorite,
    'like': Icons.favorite,
    '思考': Icons.psychology,
    '疑惑': Icons.help_outline,
    '迷茫': Icons.psychology,
    '困惑': Icons.help_outline,
    'think': Icons.psychology,
    'thinking': Icons.psychology,
    'confused': Icons.help_outline,
    'puzzled': Icons.help_outline,
    '生病': Icons.sick,
    '不舒服': Icons.sick,
    '难受': Icons.sick,
    'sick': Icons.sick,
    'ill': Icons.sick,
    'unwell': Icons.sick,
    'pain': Icons.sick,
    '无聊': Icons.bedtime_outlined,
    '没意思': Icons.bedtime_outlined,
    'bored': Icons.bedtime_outlined,
    'boring': Icons.bedtime_outlined,
  };

  static IconData? getIcon(String mood) {
    if (_moodMap.containsKey(mood)) {
      return _moodMap[mood];
    }
    final lowerMood = mood.toLowerCase();
    if (_moodMap.containsKey(lowerMood)) {
      return _moodMap[lowerMood];
    }
    for (final entry in _moodMap.entries) {
      if (mood.contains(entry.key) || entry.key.contains(mood)) {
        return entry.value;
      }
    }
    return null;
  }
}

class WeatherIcons {
  static final Map<String, IconData> _weatherMap = {
    '晴': Icons.wb_sunny,
    '晴天': Icons.wb_sunny,
    '太阳': Icons.wb_sunny,
    '阳光': Icons.wb_sunny,
    '晴朗': Icons.wb_sunny,
    'sunny': Icons.wb_sunny,
    'sun': Icons.wb_sunny,
    'clear': Icons.wb_sunny,
    'hot': Icons.wb_sunny,
    '炎热': Icons.wb_sunny,
    '热': Icons.wb_sunny,
    '暴晒': Icons.wb_sunny,
    '多云': Icons.wb_cloudy,
    '阴天': Icons.wb_cloudy,
    '阴': Icons.cloud,
    'cloudy': Icons.wb_cloudy,
    'overcast': Icons.wb_cloudy,
    'cloud': Icons.cloud,
    'clouds': Icons.cloud,
    '雨': Icons.water_drop,
    '下雨': Icons.water_drop,
    '雨天': Icons.water_drop,
    '小雨': Icons.water_drop,
    '中雨': Icons.water_drop,
    '大雨': Icons.water_drop,
    '暴雨': Icons.water_drop,
    '阵雨': Icons.water_drop,
    '雷阵雨': Icons.thunderstorm,
    'rain': Icons.water_drop,
    'rainy': Icons.water_drop,
    'drizzle': Icons.water_drop,
    'shower': Icons.water_drop,
    'downpour': Icons.water_drop,
    'storm': Icons.thunderstorm,
    'thunderstorm': Icons.thunderstorm,
    'thunder': Icons.thunderstorm,
    '雷': Icons.thunderstorm,
    '打雷': Icons.thunderstorm,
    '雪': Icons.ac_unit,
    '下雪': Icons.ac_unit,
    '雪天': Icons.ac_unit,
    '小雪': Icons.ac_unit,
    '中雪': Icons.ac_unit,
    '大雪': Icons.ac_unit,
    '暴雪': Icons.ac_unit,
    'snow': Icons.ac_unit,
    'snowy': Icons.ac_unit,
    'snowfall': Icons.ac_unit,
    'blizzard': Icons.ac_unit,
    '冰雹': Icons.ac_unit,
    'hail': Icons.ac_unit,
    '风': Icons.air,
    '大风': Icons.air,
    '微风': Icons.air,
    '刮风': Icons.air,
    '风暴': Icons.storm,
    '台风': Icons.storm,
    'wind': Icons.air,
    'windy': Icons.air,
    'breeze': Icons.air,
    'gale': Icons.air,
    'typhoon': Icons.storm,
    'hurricane': Icons.storm,
    '雾': Icons.foggy,
    '大雾': Icons.foggy,
    '雾霾': Icons.foggy,
    'fog': Icons.foggy,
    'foggy': Icons.foggy,
    'haze': Icons.foggy,
    'smog': Icons.foggy,
    'mist': Icons.foggy,
    '彩虹': Icons.looks,
    'rainbow': Icons.looks,
    '沙尘': Icons.grain,
    '沙尘暴': Icons.grain,
    'sandstorm': Icons.grain,
    'dust': Icons.grain,
    '月亮': Icons.nights_stay,
    '晚上': Icons.nights_stay,
    '夜晚': Icons.nights_stay,
    'moon': Icons.nights_stay,
    'night': Icons.nights_stay,
    'evening': Icons.nights_stay,
    '星空': Icons.nights_stay,
    'starry': Icons.nights_stay,
    '冷': Icons.thermostat,
    '寒冷': Icons.thermostat,
    'cool': Icons.thermostat,
    'cold': Icons.thermostat,
    'freezing': Icons.thermostat,
    '冰冻': Icons.thermostat,
    '冰': Icons.thermostat,
    'warm': Icons.thermostat,
    '温暖': Icons.thermostat,
    '凉爽': Icons.thermostat,
    '凉快': Icons.thermostat,
  };

  static IconData? getIcon(String weather) {
    if (_weatherMap.containsKey(weather)) {
      return _weatherMap[weather];
    }
    final lowerWeather = weather.toLowerCase();
    if (_weatherMap.containsKey(lowerWeather)) {
      return _weatherMap[lowerWeather];
    }
    for (final entry in _weatherMap.entries) {
      if (weather.contains(entry.key) || entry.key.contains(weather)) {
        return entry.value;
      }
    }
    return null;
  }
}